name: gits_http
description: Future-based library for making HTTP requests modified from http package.
version: 1.1.2
homepage: https://gits.id/
repository: https://github.com/gitsindonesia/flutter-library/tree/main/packages/gits_http

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  async: ^2.5.0
  http_parser: ^4.0.0
  meta: ^1.3.0
  path: ^1.8.2
  uuid: ^3.0.6
  equatable: ^2.0.5
  logger: ^1.1.0

  gits_inspector: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
